---

- include_tasks: centos.yml
  when: ansible_os_family == "RedHat"

- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: "Set OS dependent variables"
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: "Set listen address"
  lineinfile:
    path: "{{ www_conf_path }}"
    regexp: "listen ="
    line: "listen = 127.0.0.1:9000"
    state: present

- name: "Configure php"
  lineinfile:
    path: "{{ php_ini_path }}"
    regexp: "{{ item.param }} ="
    line: "{{ item.param }} = {{ item.value }}"
    state: present
  with_items: "{{ php_ini_configs }}"

- name: "Install php amqp plugin"
  package:
    name: "{{ php_amqp_package }}"
    state: present

- name: "Reload php-fpm"
  service:
    name: "{{ php_service_name }}"
    state: reloaded
